### ISSUE TITLE
ClassNotFoundException: org.apache.maven.cli.MavenLoggerManager

### ISSUE THREAD

**Issue by Foxswily** [hudson3-plugins/maven3-support#6]
hudson version : 3.2.1
maven plugin version : 3.0.4
maven version : 3.2.3

build log
Found mavenVersion 3.2.3 from file jar:file:/usr/local/maven/lib/maven-core-3.2.3.jar!/META-INF/maven/org.apache.maven/maven-core/pom.properties
Parsing POMs
[workspace] $ /usr/lib/jvm/java-7-oracle/bin/java -cp /data/hudson/plugins/maven-plugin/WEB-INF/lib/maven3-agent-3.0.1.jar:/usr/local/maven/boot/plexus-classworlds-2.5.1.jar org.jvnet.hudson.maven3.agent.Maven3Main /usr/local/maven /www/webapps/hudson/WEB-INF/lib/hudson-remoting-3.0.2.jar /data/hudson/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-3.0.1.jar 49557
<===[HUDSON REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /data/hudson/jobs/project/workspace/pom.xml -Dmaven.repo.local=/data/hudson/jobs/project/workspace/.repository clean compile
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:146)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:124)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:107)
	at hudson.remoting.UserRequest.perform(UserRequest.java:41)
	at hudson.remoting.Request$2.run(Request.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/cli/MavenLoggerManager
	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:73)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.cli.MavenLoggerManager
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 18 more
channel stopped
ERROR: Failed to parse POMs

**Comment by mcculls** [comment]
The stack trace above is from the [legacy Maven job type](https://github.com/hudson3-plugins/legacy-maven-support) whereas this project provides the Maven-3 build step. I'd recommend moving to the Maven-3 build step if possible because it supports more recent builds of Maven, such as 3.2.3
